# Generated by Django 3.0.4 on 2020-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('article_link', models.CharField(max_length=150)),
                ('image_link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NationalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_cases', models.IntegerField()),
                ('total_cured', models.IntegerField(default=0)),
                ('total_deaths', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_number', models.IntegerField(primary_key=True, serialize=False)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('india_confirmed_cases', models.IntegerField()),
                ('foreign_confirmed_cases', models.IntegerField()),
                ('cured_cases', models.IntegerField()),
                ('deaths_caused', models.IntegerField()),
            ],
        ),
    ]
