# Generated by Django 3.0.4 on 2020-04-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_page_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='foreign_confirmed_cases',
        ),
    ]
