# Generated by Django 3.0.4 on 2020-03-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nationaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('page_views', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='nationaldata',
            name='total_cured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nationaldata',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
    ]
