# Generated by Django 3.0.4 on 2020-03-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200330_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
